### ISSUE TITLE
Can't register now.

### ISSUE THREAD

**Issue by Minhnguyendhth8b** [seregazhuk/php-pinterest-bot#240]
Seem like the $bot->auth->register() does not work anymore.
- After register , i logged in with that email and password , but i got an error : 
"The email you entered does not belong to any account."

Please check again.

**Comment by seregazhuk** [comment]
@Minhnguyendhth8b fixed in version 5.2.3

**Comment by Minhnguyendhth8b** [comment]
@seregazhuk  Still failed : "The email you entered does not belong to any account."

**Comment by seregazhuk** [comment]
@Minhnguyendhth8b, have you used the latest library version?
I've just checked it, and it works fine. Here is my code:

```php
require 'vendor/autoload.php';

use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();
$bot->auth->register('bimutriche@housat.com', 'secret', 'test');
$bot->auth->login('bimutriche@housat.com', 'secret');
echo $bot->user->username();

```

For temp emails I use http://www.throwawaymail.com

**Comment by Minhnguyendhth8b** [comment]
@seregazhuk  Sorry , my mistake , it's all good , thanks.

**Comment by Minhnguyendhth8b** [comment]
@seregazhuk  I think in new version , we can't register again. Please recheck $bot->auth->register(). I already update new version but i meet that error again.

**Comment by seregazhuk** [comment]
Hi, @Minhnguyendhth8b 
Yes, it was issue with cookies. Update to v.5.4.4

**Comment by Minhnguyendhth8b** [comment]
@seregazhuk Nice, thanks very much. It works 👍
