### ISSUE TITLE
Comment function not working for me

### ISSUE THREAD

**Issue by newschooler** [seregazhuk/php-pinterest-bot#350]
Hey there,

first of all thank you for your great pinterest php api. I used your comment example to comment on a pin, but nothing happens. Is this function buggy?

Thank you so far

**Comment by seregazhuk** [comment]
Hi @newschooler 
I've just checked and everything works to me. Need more info.

**Comment by newschooler** [comment]
Hi @seregazhuk 
Thank you for your quick reply.

That's the code I'm using: 
`$bot = PinterestBot::create();

	// Login
	$bot->auth->login($account, $appSecret);

	$pins = $bot->pins->search($search)->toArray();

	foreach($pins as $pin) {
		
		// like pin
		$bot->pins->like($pin['id']);
		
		sleep(rand(5,10));

		if( $i % 2 == 0 && !$in_array_comments ) {// durch 2 teilbar
    		$comment = $comments[array_rand($comments)];
			$bot->comments->create($pin['id'], $comment);
			sleep(rand(5,10));
    	}

    	$i++;
		if($i == 10) {
			break;
		}
	}
	
	// Follow User
	$peopleToFollow = $bot->pins->search($search)->toArray();
	foreach($peopleToFollow as $user) {
		$bot->pinners->follow($user['id']);
		
		sleep(rand(5,10));
		
		$j++;
		if( $j == 5 ) {
			break;
		}
	}`

**Comment by ltiwana** [comment]
I have the same issue.

**Comment by seregazhuk** [comment]
@ltiwana @newschooler fixed. Please update to version `5.6.7`

**Comment by ltiwana** [comment]
Thank you very much for your help. I just updated an tried again but it didn't work.  Here is my code:

`date_default_timezone_set('America/Toronto');`
`require __DIR__ . '/vendor/autoload.php';`
`use seregazhuk\PinterestBot\Factories\PinterestBot;`

`$bot = PinterestBot::create();`

`$pins = $bot->pins->search('cats', 100)->toArray();`

`foreach($pins as $pin) { `
`      $bot->comments->create($pin['id'], 'Nice');	`
`}`

**Comment by seregazhuk** [comment]
@ltiwana yes, I've finally found the problem. It is with *liking*. Now fixed with version `5.6.8`. But it looks like Pinterest has disabled like/dislike for pins? I cannot find it in the browser. Do you have any idea?

**Comment by ltiwana** [comment]
@seregazhuk nice! I will give it another try. Yes, pinterest has removed the like function as they are trying to differentiate from other social media platforms. I don't use that functionality. https://help.pinterest.com/en/feedback-about-removing-likes

**Comment by ltiwana** [comment]
I just tried again with new update `5.6.8` but still no luck. Interesting thing is that after every comment `$bot->comments->create($pin['id'], 'Nice');`  `[comment_count]`  increasing but when I go the pin on the browser I don't see any comments.

**Comment by seregazhuk** [comment]
Maybe the issue is with the types? Try this:

```php
var_dump($bot->comments->create('242209286193614751', 'So cute'));
```

Does it work for you? Very strange, when passing pinId as a number, it returns an error.

**Comment by ltiwana** [comment]
I will give this try soon.

**Comment by ltiwana** [comment]
by creating a new project my comment posting is working as well now.
